# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: junykim <junykim@student.42seoul.kr>       +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/01/15 11:28:15 by junykim           #+#    #+#              #
#    Updated: 2023/01/18 12:13:24 by junykim          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

#Variable
NAME	= megaphone
CC		= c++
CFLAGS	= -Wall -Wextra -Werror -std=c++98

# srcs

# rules
all : $(NAME)

.PHONY : all re fclean clean

